// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewWalletRequest struct {
	ChainID              int64    `protobuf:"varint,1,opt,name=chainID" json:"chainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewWalletRequest) Reset()         { *m = NewWalletRequest{} }
func (m *NewWalletRequest) String() string { return proto.CompactTextString(m) }
func (*NewWalletRequest) ProtoMessage()    {}
func (*NewWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{0}
}
func (m *NewWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewWalletRequest.Unmarshal(m, b)
}
func (m *NewWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewWalletRequest.Marshal(b, m, deterministic)
}
func (dst *NewWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewWalletRequest.Merge(dst, src)
}
func (m *NewWalletRequest) XXX_Size() int {
	return xxx_messageInfo_NewWalletRequest.Size(m)
}
func (m *NewWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewWalletRequest proto.InternalMessageInfo

func (m *NewWalletRequest) GetChainID() int64 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

type NewWalletResponse struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewWalletResponse) Reset()         { *m = NewWalletResponse{} }
func (m *NewWalletResponse) String() string { return proto.CompactTextString(m) }
func (*NewWalletResponse) ProtoMessage()    {}
func (*NewWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{1}
}
func (m *NewWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewWalletResponse.Unmarshal(m, b)
}
func (m *NewWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewWalletResponse.Marshal(b, m, deterministic)
}
func (dst *NewWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewWalletResponse.Merge(dst, src)
}
func (m *NewWalletResponse) XXX_Size() int {
	return xxx_messageInfo_NewWalletResponse.Size(m)
}
func (m *NewWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewWalletResponse proto.InternalMessageInfo

func (m *NewWalletResponse) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type UnlockRequest struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=privateKey" json:"privateKey,omitempty"`
	ChainID              int64    `protobuf:"varint,2,opt,name=chainID" json:"chainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockRequest) Reset()         { *m = UnlockRequest{} }
func (m *UnlockRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockRequest) ProtoMessage()    {}
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{2}
}
func (m *UnlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockRequest.Unmarshal(m, b)
}
func (m *UnlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockRequest.Marshal(b, m, deterministic)
}
func (dst *UnlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockRequest.Merge(dst, src)
}
func (m *UnlockRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockRequest.Size(m)
}
func (m *UnlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockRequest proto.InternalMessageInfo

func (m *UnlockRequest) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *UnlockRequest) GetChainID() int64 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

type UnlockResponse struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockResponse) Reset()         { *m = UnlockResponse{} }
func (m *UnlockResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockResponse) ProtoMessage()    {}
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{3}
}
func (m *UnlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockResponse.Unmarshal(m, b)
}
func (m *UnlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockResponse.Marshal(b, m, deterministic)
}
func (dst *UnlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockResponse.Merge(dst, src)
}
func (m *UnlockResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockResponse.Size(m)
}
func (m *UnlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockResponse proto.InternalMessageInfo

func (m *UnlockResponse) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type SignTransferRequest struct {
	Address              *Address  `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Transfer             *Transfer `protobuf:"bytes,2,opt,name=transfer" json:"transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignTransferRequest) Reset()         { *m = SignTransferRequest{} }
func (m *SignTransferRequest) String() string { return proto.CompactTextString(m) }
func (*SignTransferRequest) ProtoMessage()    {}
func (*SignTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{4}
}
func (m *SignTransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransferRequest.Unmarshal(m, b)
}
func (m *SignTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransferRequest.Marshal(b, m, deterministic)
}
func (dst *SignTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransferRequest.Merge(dst, src)
}
func (m *SignTransferRequest) XXX_Size() int {
	return xxx_messageInfo_SignTransferRequest.Size(m)
}
func (m *SignTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransferRequest proto.InternalMessageInfo

func (m *SignTransferRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SignTransferRequest) GetTransfer() *Transfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

type SignTransferResponse struct {
	Transfer             *Transfer `protobuf:"bytes,1,opt,name=transfer" json:"transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignTransferResponse) Reset()         { *m = SignTransferResponse{} }
func (m *SignTransferResponse) String() string { return proto.CompactTextString(m) }
func (*SignTransferResponse) ProtoMessage()    {}
func (*SignTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{5}
}
func (m *SignTransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransferResponse.Unmarshal(m, b)
}
func (m *SignTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransferResponse.Marshal(b, m, deterministic)
}
func (dst *SignTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransferResponse.Merge(dst, src)
}
func (m *SignTransferResponse) XXX_Size() int {
	return xxx_messageInfo_SignTransferResponse.Size(m)
}
func (m *SignTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransferResponse proto.InternalMessageInfo

func (m *SignTransferResponse) GetTransfer() *Transfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

type SignVoteRequest struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Vote                 *Vote    `protobuf:"bytes,2,opt,name=vote" json:"vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignVoteRequest) Reset()         { *m = SignVoteRequest{} }
func (m *SignVoteRequest) String() string { return proto.CompactTextString(m) }
func (*SignVoteRequest) ProtoMessage()    {}
func (*SignVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{6}
}
func (m *SignVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignVoteRequest.Unmarshal(m, b)
}
func (m *SignVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignVoteRequest.Marshal(b, m, deterministic)
}
func (dst *SignVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignVoteRequest.Merge(dst, src)
}
func (m *SignVoteRequest) XXX_Size() int {
	return xxx_messageInfo_SignVoteRequest.Size(m)
}
func (m *SignVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignVoteRequest proto.InternalMessageInfo

func (m *SignVoteRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SignVoteRequest) GetVote() *Vote {
	if m != nil {
		return m.Vote
	}
	return nil
}

type SignVoteResponse struct {
	Vote                 *Vote    `protobuf:"bytes,1,opt,name=vote" json:"vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignVoteResponse) Reset()         { *m = SignVoteResponse{} }
func (m *SignVoteResponse) String() string { return proto.CompactTextString(m) }
func (*SignVoteResponse) ProtoMessage()    {}
func (*SignVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{7}
}
func (m *SignVoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignVoteResponse.Unmarshal(m, b)
}
func (m *SignVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignVoteResponse.Marshal(b, m, deterministic)
}
func (dst *SignVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignVoteResponse.Merge(dst, src)
}
func (m *SignVoteResponse) XXX_Size() int {
	return xxx_messageInfo_SignVoteResponse.Size(m)
}
func (m *SignVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignVoteResponse proto.InternalMessageInfo

func (m *SignVoteResponse) GetVote() *Vote {
	if m != nil {
		return m.Vote
	}
	return nil
}

type DecodeAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	ChainID              int64    `protobuf:"varint,2,opt,name=chainID" json:"chainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecodeAddressRequest) Reset()         { *m = DecodeAddressRequest{} }
func (m *DecodeAddressRequest) String() string { return proto.CompactTextString(m) }
func (*DecodeAddressRequest) ProtoMessage()    {}
func (*DecodeAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{8}
}
func (m *DecodeAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecodeAddressRequest.Unmarshal(m, b)
}
func (m *DecodeAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecodeAddressRequest.Marshal(b, m, deterministic)
}
func (dst *DecodeAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecodeAddressRequest.Merge(dst, src)
}
func (m *DecodeAddressRequest) XXX_Size() int {
	return xxx_messageInfo_DecodeAddressRequest.Size(m)
}
func (m *DecodeAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecodeAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecodeAddressRequest proto.InternalMessageInfo

func (m *DecodeAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DecodeAddressRequest) GetChainID() int64 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

type DecodeAddressResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	ChainID              string   `protobuf:"bytes,2,opt,name=chainID" json:"chainID,omitempty"`
	IsTestnet            bool     `protobuf:"varint,3,opt,name=isTestnet" json:"isTestnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecodeAddressResponse) Reset()         { *m = DecodeAddressResponse{} }
func (m *DecodeAddressResponse) String() string { return proto.CompactTextString(m) }
func (*DecodeAddressResponse) ProtoMessage()    {}
func (*DecodeAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{9}
}
func (m *DecodeAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecodeAddressResponse.Unmarshal(m, b)
}
func (m *DecodeAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecodeAddressResponse.Marshal(b, m, deterministic)
}
func (dst *DecodeAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecodeAddressResponse.Merge(dst, src)
}
func (m *DecodeAddressResponse) XXX_Size() int {
	return xxx_messageInfo_DecodeAddressResponse.Size(m)
}
func (m *DecodeAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecodeAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecodeAddressResponse proto.InternalMessageInfo

func (m *DecodeAddressResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *DecodeAddressResponse) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *DecodeAddressResponse) GetIsTestnet() bool {
	if m != nil {
		return m.IsTestnet
	}
	return false
}

type Address struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=publicKey" json:"publicKey,omitempty"`
	PrivateKey           string   `protobuf:"bytes,2,opt,name=privateKey" json:"privateKey,omitempty"`
	RawAddress           string   `protobuf:"bytes,3,opt,name=rawAddress" json:"rawAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{10}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Address) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *Address) GetRawAddress() string {
	if m != nil {
		return m.RawAddress
	}
	return ""
}

type SignExecutionRequest struct {
	Address              *Address   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Execution            *Execution `protobuf:"bytes,2,opt,name=execution" json:"execution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignExecutionRequest) Reset()         { *m = SignExecutionRequest{} }
func (m *SignExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*SignExecutionRequest) ProtoMessage()    {}
func (*SignExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{11}
}
func (m *SignExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignExecutionRequest.Unmarshal(m, b)
}
func (m *SignExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignExecutionRequest.Marshal(b, m, deterministic)
}
func (dst *SignExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignExecutionRequest.Merge(dst, src)
}
func (m *SignExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_SignExecutionRequest.Size(m)
}
func (m *SignExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignExecutionRequest proto.InternalMessageInfo

func (m *SignExecutionRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SignExecutionRequest) GetExecution() *Execution {
	if m != nil {
		return m.Execution
	}
	return nil
}

type SignExecutionResponse struct {
	Execution            *Execution `protobuf:"bytes,1,opt,name=execution" json:"execution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignExecutionResponse) Reset()         { *m = SignExecutionResponse{} }
func (m *SignExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*SignExecutionResponse) ProtoMessage()    {}
func (*SignExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{12}
}
func (m *SignExecutionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignExecutionResponse.Unmarshal(m, b)
}
func (m *SignExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignExecutionResponse.Marshal(b, m, deterministic)
}
func (dst *SignExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignExecutionResponse.Merge(dst, src)
}
func (m *SignExecutionResponse) XXX_Size() int {
	return xxx_messageInfo_SignExecutionResponse.Size(m)
}
func (m *SignExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignExecutionResponse proto.InternalMessageInfo

func (m *SignExecutionResponse) GetExecution() *Execution {
	if m != nil {
		return m.Execution
	}
	return nil
}

type SignCreateDepositRequest struct {
	Address              *Address       `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	CreateDeposit        *CreateDeposit `protobuf:"bytes,2,opt,name=createDeposit" json:"createDeposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignCreateDepositRequest) Reset()         { *m = SignCreateDepositRequest{} }
func (m *SignCreateDepositRequest) String() string { return proto.CompactTextString(m) }
func (*SignCreateDepositRequest) ProtoMessage()    {}
func (*SignCreateDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{13}
}
func (m *SignCreateDepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignCreateDepositRequest.Unmarshal(m, b)
}
func (m *SignCreateDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignCreateDepositRequest.Marshal(b, m, deterministic)
}
func (dst *SignCreateDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignCreateDepositRequest.Merge(dst, src)
}
func (m *SignCreateDepositRequest) XXX_Size() int {
	return xxx_messageInfo_SignCreateDepositRequest.Size(m)
}
func (m *SignCreateDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignCreateDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignCreateDepositRequest proto.InternalMessageInfo

func (m *SignCreateDepositRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SignCreateDepositRequest) GetCreateDeposit() *CreateDeposit {
	if m != nil {
		return m.CreateDeposit
	}
	return nil
}

type SignCreateDepositResponse struct {
	CreateDeposit        *CreateDeposit `protobuf:"bytes,1,opt,name=createDeposit" json:"createDeposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignCreateDepositResponse) Reset()         { *m = SignCreateDepositResponse{} }
func (m *SignCreateDepositResponse) String() string { return proto.CompactTextString(m) }
func (*SignCreateDepositResponse) ProtoMessage()    {}
func (*SignCreateDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{14}
}
func (m *SignCreateDepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignCreateDepositResponse.Unmarshal(m, b)
}
func (m *SignCreateDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignCreateDepositResponse.Marshal(b, m, deterministic)
}
func (dst *SignCreateDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignCreateDepositResponse.Merge(dst, src)
}
func (m *SignCreateDepositResponse) XXX_Size() int {
	return xxx_messageInfo_SignCreateDepositResponse.Size(m)
}
func (m *SignCreateDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignCreateDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignCreateDepositResponse proto.InternalMessageInfo

func (m *SignCreateDepositResponse) GetCreateDeposit() *CreateDeposit {
	if m != nil {
		return m.CreateDeposit
	}
	return nil
}

type SignSettleDepositRequest struct {
	Address              *Address       `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	SettleDeposit        *SettleDeposit `protobuf:"bytes,2,opt,name=settleDeposit" json:"settleDeposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignSettleDepositRequest) Reset()         { *m = SignSettleDepositRequest{} }
func (m *SignSettleDepositRequest) String() string { return proto.CompactTextString(m) }
func (*SignSettleDepositRequest) ProtoMessage()    {}
func (*SignSettleDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{15}
}
func (m *SignSettleDepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignSettleDepositRequest.Unmarshal(m, b)
}
func (m *SignSettleDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignSettleDepositRequest.Marshal(b, m, deterministic)
}
func (dst *SignSettleDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignSettleDepositRequest.Merge(dst, src)
}
func (m *SignSettleDepositRequest) XXX_Size() int {
	return xxx_messageInfo_SignSettleDepositRequest.Size(m)
}
func (m *SignSettleDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignSettleDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignSettleDepositRequest proto.InternalMessageInfo

func (m *SignSettleDepositRequest) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *SignSettleDepositRequest) GetSettleDeposit() *SettleDeposit {
	if m != nil {
		return m.SettleDeposit
	}
	return nil
}

type SignSettleDepositResponse struct {
	SettleDeposit        *SettleDeposit `protobuf:"bytes,1,opt,name=settleDeposit" json:"settleDeposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignSettleDepositResponse) Reset()         { *m = SignSettleDepositResponse{} }
func (m *SignSettleDepositResponse) String() string { return proto.CompactTextString(m) }
func (*SignSettleDepositResponse) ProtoMessage()    {}
func (*SignSettleDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{16}
}
func (m *SignSettleDepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignSettleDepositResponse.Unmarshal(m, b)
}
func (m *SignSettleDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignSettleDepositResponse.Marshal(b, m, deterministic)
}
func (dst *SignSettleDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignSettleDepositResponse.Merge(dst, src)
}
func (m *SignSettleDepositResponse) XXX_Size() int {
	return xxx_messageInfo_SignSettleDepositResponse.Size(m)
}
func (m *SignSettleDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignSettleDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignSettleDepositResponse proto.InternalMessageInfo

func (m *SignSettleDepositResponse) GetSettleDeposit() *SettleDeposit {
	if m != nil {
		return m.SettleDeposit
	}
	return nil
}

type Transfer struct {
	Nonce                int64    `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
	Sender               string   `protobuf:"bytes,4,opt,name=sender" json:"sender,omitempty"`
	Recipient            string   `protobuf:"bytes,5,opt,name=recipient" json:"recipient,omitempty"`
	Payload              string   `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`
	GasLimit             int64    `protobuf:"varint,7,opt,name=gasLimit" json:"gasLimit,omitempty"`
	GasPrice             string   `protobuf:"bytes,8,opt,name=gasPrice" json:"gasPrice,omitempty"`
	Version              int64    `protobuf:"varint,9,opt,name=version" json:"version,omitempty"`
	IsCoinbase           bool     `protobuf:"varint,10,opt,name=isCoinbase" json:"isCoinbase,omitempty"`
	SenderPubKey         string   `protobuf:"bytes,11,opt,name=senderPubKey" json:"senderPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{17}
}
func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (dst *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(dst, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transfer) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transfer) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Transfer) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Transfer) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Transfer) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *Transfer) GetGasLimit() int64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Transfer) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Transfer) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transfer) GetIsCoinbase() bool {
	if m != nil {
		return m.IsCoinbase
	}
	return false
}

func (m *Transfer) GetSenderPubKey() string {
	if m != nil {
		return m.SenderPubKey
	}
	return ""
}

type Vote struct {
	Nonce                int64    `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	VoterAddress         string   `protobuf:"bytes,3,opt,name=voterAddress" json:"voterAddress,omitempty"`
	VoteeAddress         string   `protobuf:"bytes,4,opt,name=voteeAddress" json:"voteeAddress,omitempty"`
	GasLimit             int64    `protobuf:"varint,5,opt,name=gasLimit" json:"gasLimit,omitempty"`
	GasPrice             string   `protobuf:"bytes,6,opt,name=gasPrice" json:"gasPrice,omitempty"`
	Version              int64    `protobuf:"varint,7,opt,name=version" json:"version,omitempty"`
	SelfPubKey           string   `protobuf:"bytes,8,opt,name=selfPubKey" json:"selfPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{18}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (dst *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(dst, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Vote) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Vote) GetVoterAddress() string {
	if m != nil {
		return m.VoterAddress
	}
	return ""
}

func (m *Vote) GetVoteeAddress() string {
	if m != nil {
		return m.VoteeAddress
	}
	return ""
}

func (m *Vote) GetGasLimit() int64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Vote) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Vote) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Vote) GetSelfPubKey() string {
	if m != nil {
		return m.SelfPubKey
	}
	return ""
}

type Execution struct {
	Nonce                int64    `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
	Executor             string   `protobuf:"bytes,4,opt,name=executor" json:"executor,omitempty"`
	Contract             string   `protobuf:"bytes,5,opt,name=contract" json:"contract,omitempty"`
	GasLimit             int64    `protobuf:"varint,6,opt,name=gasLimit" json:"gasLimit,omitempty"`
	GasPrice             string   `protobuf:"bytes,7,opt,name=gasPrice" json:"gasPrice,omitempty"`
	Data                 string   `protobuf:"bytes,8,opt,name=data" json:"data,omitempty"`
	Version              int64    `protobuf:"varint,9,opt,name=version" json:"version,omitempty"`
	ExecutorPubKey       string   `protobuf:"bytes,10,opt,name=executorPubKey" json:"executorPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{19}
}
func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (dst *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(dst, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Execution) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Execution) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Execution) GetExecutor() string {
	if m != nil {
		return m.Executor
	}
	return ""
}

func (m *Execution) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Execution) GetGasLimit() int64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Execution) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Execution) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Execution) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Execution) GetExecutorPubKey() string {
	if m != nil {
		return m.ExecutorPubKey
	}
	return ""
}

type CreateDeposit struct {
	Nonce                int64    `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
	Sender               string   `protobuf:"bytes,4,opt,name=sender" json:"sender,omitempty"`
	Recipient            string   `protobuf:"bytes,5,opt,name=recipient" json:"recipient,omitempty"`
	GasLimit             int64    `protobuf:"varint,6,opt,name=gasLimit" json:"gasLimit,omitempty"`
	GasPrice             string   `protobuf:"bytes,7,opt,name=gasPrice" json:"gasPrice,omitempty"`
	Version              int64    `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
	SenderPubKey         string   `protobuf:"bytes,9,opt,name=senderPubKey" json:"senderPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeposit) Reset()         { *m = CreateDeposit{} }
func (m *CreateDeposit) String() string { return proto.CompactTextString(m) }
func (*CreateDeposit) ProtoMessage()    {}
func (*CreateDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{20}
}
func (m *CreateDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeposit.Unmarshal(m, b)
}
func (m *CreateDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeposit.Marshal(b, m, deterministic)
}
func (dst *CreateDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeposit.Merge(dst, src)
}
func (m *CreateDeposit) XXX_Size() int {
	return xxx_messageInfo_CreateDeposit.Size(m)
}
func (m *CreateDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeposit proto.InternalMessageInfo

func (m *CreateDeposit) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CreateDeposit) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *CreateDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *CreateDeposit) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *CreateDeposit) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *CreateDeposit) GetGasLimit() int64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *CreateDeposit) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *CreateDeposit) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CreateDeposit) GetSenderPubKey() string {
	if m != nil {
		return m.SenderPubKey
	}
	return ""
}

type SettleDeposit struct {
	Nonce                int64    `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount" json:"amount,omitempty"`
	Index                int64    `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	Sender               string   `protobuf:"bytes,5,opt,name=sender" json:"sender,omitempty"`
	Recipient            string   `protobuf:"bytes,6,opt,name=recipient" json:"recipient,omitempty"`
	GasLimit             int64    `protobuf:"varint,7,opt,name=gasLimit" json:"gasLimit,omitempty"`
	GasPrice             string   `protobuf:"bytes,8,opt,name=gasPrice" json:"gasPrice,omitempty"`
	Version              int64    `protobuf:"varint,9,opt,name=version" json:"version,omitempty"`
	SenderPubKey         string   `protobuf:"bytes,10,opt,name=senderPubKey" json:"senderPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleDeposit) Reset()         { *m = SettleDeposit{} }
func (m *SettleDeposit) String() string { return proto.CompactTextString(m) }
func (*SettleDeposit) ProtoMessage()    {}
func (*SettleDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8be5926e11f626b0, []int{21}
}
func (m *SettleDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleDeposit.Unmarshal(m, b)
}
func (m *SettleDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleDeposit.Marshal(b, m, deterministic)
}
func (dst *SettleDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleDeposit.Merge(dst, src)
}
func (m *SettleDeposit) XXX_Size() int {
	return xxx_messageInfo_SettleDeposit.Size(m)
}
func (m *SettleDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_SettleDeposit proto.InternalMessageInfo

func (m *SettleDeposit) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *SettleDeposit) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SettleDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *SettleDeposit) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SettleDeposit) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SettleDeposit) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *SettleDeposit) GetGasLimit() int64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *SettleDeposit) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *SettleDeposit) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SettleDeposit) GetSenderPubKey() string {
	if m != nil {
		return m.SenderPubKey
	}
	return ""
}

func init() {
	proto.RegisterType((*NewWalletRequest)(nil), "pb.NewWalletRequest")
	proto.RegisterType((*NewWalletResponse)(nil), "pb.NewWalletResponse")
	proto.RegisterType((*UnlockRequest)(nil), "pb.UnlockRequest")
	proto.RegisterType((*UnlockResponse)(nil), "pb.UnlockResponse")
	proto.RegisterType((*SignTransferRequest)(nil), "pb.SignTransferRequest")
	proto.RegisterType((*SignTransferResponse)(nil), "pb.SignTransferResponse")
	proto.RegisterType((*SignVoteRequest)(nil), "pb.SignVoteRequest")
	proto.RegisterType((*SignVoteResponse)(nil), "pb.SignVoteResponse")
	proto.RegisterType((*DecodeAddressRequest)(nil), "pb.DecodeAddressRequest")
	proto.RegisterType((*DecodeAddressResponse)(nil), "pb.DecodeAddressResponse")
	proto.RegisterType((*Address)(nil), "pb.Address")
	proto.RegisterType((*SignExecutionRequest)(nil), "pb.SignExecutionRequest")
	proto.RegisterType((*SignExecutionResponse)(nil), "pb.SignExecutionResponse")
	proto.RegisterType((*SignCreateDepositRequest)(nil), "pb.SignCreateDepositRequest")
	proto.RegisterType((*SignCreateDepositResponse)(nil), "pb.SignCreateDepositResponse")
	proto.RegisterType((*SignSettleDepositRequest)(nil), "pb.SignSettleDepositRequest")
	proto.RegisterType((*SignSettleDepositResponse)(nil), "pb.SignSettleDepositResponse")
	proto.RegisterType((*Transfer)(nil), "pb.Transfer")
	proto.RegisterType((*Vote)(nil), "pb.Vote")
	proto.RegisterType((*Execution)(nil), "pb.Execution")
	proto.RegisterType((*CreateDeposit)(nil), "pb.CreateDeposit")
	proto.RegisterType((*SettleDeposit)(nil), "pb.SettleDeposit")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WalletService service

type WalletServiceClient interface {
	NewWallet(ctx context.Context, in *NewWalletRequest, opts ...grpc.CallOption) (*NewWalletResponse, error)
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
	SignTransfer(ctx context.Context, in *SignTransferRequest, opts ...grpc.CallOption) (*SignTransferResponse, error)
	SignVote(ctx context.Context, in *SignVoteRequest, opts ...grpc.CallOption) (*SignVoteResponse, error)
	SignExecution(ctx context.Context, in *SignExecutionRequest, opts ...grpc.CallOption) (*SignExecutionResponse, error)
	SignCreateDeposit(ctx context.Context, in *SignCreateDepositRequest, opts ...grpc.CallOption) (*SignCreateDepositResponse, error)
	SignSettleDeposit(ctx context.Context, in *SignSettleDepositRequest, opts ...grpc.CallOption) (*SignSettleDepositResponse, error)
	DecodeAddress(ctx context.Context, in *DecodeAddressRequest, opts ...grpc.CallOption) (*DecodeAddressResponse, error)
}

type walletServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletServiceClient(cc *grpc.ClientConn) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) NewWallet(ctx context.Context, in *NewWalletRequest, opts ...grpc.CallOption) (*NewWalletResponse, error) {
	out := new(NewWalletResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/NewWallet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	out := new(UnlockResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/Unlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SignTransfer(ctx context.Context, in *SignTransferRequest, opts ...grpc.CallOption) (*SignTransferResponse, error) {
	out := new(SignTransferResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/SignTransfer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SignVote(ctx context.Context, in *SignVoteRequest, opts ...grpc.CallOption) (*SignVoteResponse, error) {
	out := new(SignVoteResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/SignVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SignExecution(ctx context.Context, in *SignExecutionRequest, opts ...grpc.CallOption) (*SignExecutionResponse, error) {
	out := new(SignExecutionResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/SignExecution", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SignCreateDeposit(ctx context.Context, in *SignCreateDepositRequest, opts ...grpc.CallOption) (*SignCreateDepositResponse, error) {
	out := new(SignCreateDepositResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/SignCreateDeposit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SignSettleDeposit(ctx context.Context, in *SignSettleDepositRequest, opts ...grpc.CallOption) (*SignSettleDepositResponse, error) {
	out := new(SignSettleDepositResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/SignSettleDeposit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) DecodeAddress(ctx context.Context, in *DecodeAddressRequest, opts ...grpc.CallOption) (*DecodeAddressResponse, error) {
	out := new(DecodeAddressResponse)
	err := grpc.Invoke(ctx, "/pb.walletService/DecodeAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WalletService service

type WalletServiceServer interface {
	NewWallet(context.Context, *NewWalletRequest) (*NewWalletResponse, error)
	Unlock(context.Context, *UnlockRequest) (*UnlockResponse, error)
	SignTransfer(context.Context, *SignTransferRequest) (*SignTransferResponse, error)
	SignVote(context.Context, *SignVoteRequest) (*SignVoteResponse, error)
	SignExecution(context.Context, *SignExecutionRequest) (*SignExecutionResponse, error)
	SignCreateDeposit(context.Context, *SignCreateDepositRequest) (*SignCreateDepositResponse, error)
	SignSettleDeposit(context.Context, *SignSettleDepositRequest) (*SignSettleDepositResponse, error)
	DecodeAddress(context.Context, *DecodeAddressRequest) (*DecodeAddressResponse, error)
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_NewWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).NewWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/NewWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).NewWallet(ctx, req.(*NewWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/Unlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SignTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SignTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/SignTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SignTransfer(ctx, req.(*SignTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SignVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SignVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/SignVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SignVote(ctx, req.(*SignVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SignExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SignExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/SignExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SignExecution(ctx, req.(*SignExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SignCreateDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignCreateDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SignCreateDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/SignCreateDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SignCreateDeposit(ctx, req.(*SignCreateDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SignSettleDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignSettleDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SignSettleDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/SignSettleDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SignSettleDeposit(ctx, req.(*SignSettleDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_DecodeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DecodeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.walletService/DecodeAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DecodeAddress(ctx, req.(*DecodeAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.walletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewWallet",
			Handler:    _WalletService_NewWallet_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _WalletService_Unlock_Handler,
		},
		{
			MethodName: "SignTransfer",
			Handler:    _WalletService_SignTransfer_Handler,
		},
		{
			MethodName: "SignVote",
			Handler:    _WalletService_SignVote_Handler,
		},
		{
			MethodName: "SignExecution",
			Handler:    _WalletService_SignExecution_Handler,
		},
		{
			MethodName: "SignCreateDeposit",
			Handler:    _WalletService_SignCreateDeposit_Handler,
		},
		{
			MethodName: "SignSettleDeposit",
			Handler:    _WalletService_SignSettleDeposit_Handler,
		},
		{
			MethodName: "DecodeAddress",
			Handler:    _WalletService_DecodeAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_8be5926e11f626b0) }

var fileDescriptor_rpc_8be5926e11f626b0 = []byte{
	// 934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x5f, 0x6f, 0xdc, 0x44,
	0x10, 0xaf, 0x2f, 0xf7, 0xc7, 0x9e, 0xe4, 0x4a, 0xb3, 0xbd, 0x80, 0x7b, 0x0a, 0x55, 0x65, 0x09,
	0x14, 0x09, 0x14, 0x41, 0x78, 0x88, 0xd4, 0x27, 0xaa, 0x04, 0xa4, 0x02, 0x42, 0x95, 0x13, 0xca,
	0xf3, 0x9e, 0x6f, 0x92, 0x18, 0xae, 0xb6, 0xf1, 0xee, 0x25, 0x2d, 0x5f, 0x80, 0x4f, 0xd1, 0x6f,
	0xc1, 0x23, 0x1f, 0x8b, 0x0f, 0x80, 0xf6, 0xaf, 0x77, 0x7d, 0xce, 0x91, 0x44, 0x79, 0xe8, 0xdb,
	0xcd, 0xec, 0xcc, 0x6f, 0x67, 0x7e, 0x9e, 0x99, 0x9d, 0x83, 0xa8, 0xae, 0xb2, 0xfd, 0xaa, 0x2e,
	0x79, 0x49, 0x7a, 0xd5, 0x2c, 0xf9, 0x12, 0x1e, 0xfd, 0x8c, 0x57, 0xbf, 0xd2, 0xc5, 0x02, 0x79,
	0x8a, 0x7f, 0x2c, 0x91, 0x71, 0x12, 0xc3, 0x28, 0xbb, 0xa0, 0x79, 0xf1, 0xf2, 0x38, 0x0e, 0x9e,
	0x05, 0x7b, 0x1b, 0xa9, 0x11, 0x93, 0xe7, 0xb0, 0xed, 0x58, 0xb3, 0xaa, 0x2c, 0x18, 0x92, 0xcf,
	0x60, 0x44, 0xe7, 0xf3, 0x1a, 0x19, 0x93, 0xe6, 0x9b, 0x07, 0x9b, 0xfb, 0xd5, 0x6c, 0xff, 0x85,
	0x52, 0xa5, 0xe6, 0x2c, 0x79, 0x09, 0xe3, 0x5f, 0x8a, 0x45, 0x99, 0xfd, 0x6e, 0xae, 0x79, 0x0a,
	0x50, 0xd5, 0xf9, 0x25, 0xe5, 0xf8, 0x23, 0xbe, 0x93, 0xae, 0x51, 0xea, 0x68, 0xdc, 0x30, 0x7a,
	0x7e, 0x18, 0x87, 0xf0, 0xd0, 0x40, 0xdd, 0x2e, 0x86, 0x33, 0x78, 0x7c, 0x92, 0x9f, 0x17, 0xa7,
	0x35, 0x2d, 0xd8, 0x19, 0xd6, 0x26, 0x92, 0x9b, 0x79, 0x93, 0x3d, 0x08, 0xb9, 0xf6, 0x94, 0x11,
	0x6d, 0x1e, 0x6c, 0x09, 0x3b, 0x8b, 0x66, 0x4f, 0x93, 0x6f, 0x61, 0xe2, 0xdf, 0xa3, 0xc3, 0x74,
	0x11, 0x82, 0xb5, 0x08, 0xaf, 0xe1, 0x23, 0x81, 0xf0, 0xba, 0xe4, 0x78, 0xcb, 0x28, 0x77, 0xa1,
	0x7f, 0x59, 0x72, 0xd4, 0x11, 0x86, 0xc2, 0x46, 0xa2, 0x48, 0x6d, 0xf2, 0x15, 0x3c, 0x6a, 0x70,
	0x75, 0x54, 0xc6, 0x23, 0xe8, 0xf4, 0xf8, 0x01, 0x26, 0xc7, 0x98, 0x95, 0x73, 0x34, 0x37, 0x35,
	0x55, 0xe2, 0x86, 0x13, 0x35, 0x11, 0x5c, 0xff, 0xe1, 0x32, 0xd8, 0x69, 0x61, 0xe9, 0x10, 0x08,
	0xf4, 0x2f, 0x28, 0xbb, 0xd0, 0x48, 0xf2, 0x77, 0x1b, 0x26, 0xb2, 0x30, 0x64, 0x17, 0xa2, 0x9c,
	0x9d, 0x22, 0xe3, 0x05, 0xf2, 0x78, 0xe3, 0x59, 0xb0, 0x17, 0xa6, 0x8d, 0x22, 0x39, 0x87, 0xd1,
	0x0b, 0xcb, 0x45, 0x54, 0x2d, 0x67, 0x8b, 0x3c, 0x6b, 0x2a, 0xac, 0x51, 0xb4, 0x0a, 0xb0, 0xb7,
	0x52, 0x80, 0x4f, 0x01, 0x6a, 0x7a, 0xa5, 0xb1, 0xe4, 0x3d, 0x51, 0xea, 0x68, 0x92, 0xdf, 0xd4,
	0x57, 0xfe, 0xee, 0x2d, 0x66, 0x4b, 0x9e, 0x97, 0xc5, 0x2d, 0x3f, 0xd4, 0x17, 0x10, 0xa1, 0x71,
	0xd5, 0x5f, 0x6b, 0x2c, 0x0c, 0x1b, 0xbc, 0xe6, 0x3c, 0x39, 0x86, 0x9d, 0xd6, 0x5d, 0x9a, 0x39,
	0x0f, 0x25, 0xf8, 0x1f, 0x94, 0x3f, 0x21, 0x16, 0x28, 0x47, 0x35, 0x52, 0x8e, 0xc7, 0x58, 0x95,
	0x2c, 0xe7, 0xb7, 0x8c, 0xfa, 0x10, 0xc6, 0x99, 0xeb, 0xae, 0x23, 0xdf, 0x16, 0xc6, 0x3e, 0xae,
	0x6f, 0x97, 0x9c, 0xc2, 0x93, 0x8e, 0xbb, 0x75, 0x16, 0x2b, 0xa8, 0xc1, 0x0d, 0x51, 0x75, 0x46,
	0x27, 0xc8, 0xf9, 0xe2, 0xee, 0x19, 0x31, 0xd7, 0xdd, 0xcd, 0xc8, 0xc7, 0xf5, 0xed, 0x4c, 0x46,
	0xad, 0xbb, 0x9b, 0x8c, 0x7c, 0xd4, 0xe0, 0x86, 0xa8, 0xff, 0xf4, 0x20, 0x34, 0x03, 0x81, 0x4c,
	0x60, 0x50, 0x94, 0x45, 0x86, 0x7a, 0x10, 0x2b, 0x41, 0x94, 0x35, 0xcb, 0xcf, 0x0b, 0xca, 0x97,
	0x35, 0xea, 0xba, 0x6d, 0x14, 0xe4, 0x63, 0x18, 0xd2, 0x37, 0xe5, 0xb2, 0xe0, 0xba, 0x64, 0xb5,
	0x24, 0xf4, 0x0c, 0x8b, 0x39, 0xd6, 0x71, 0x5f, 0xe9, 0x95, 0x24, 0xd0, 0x6a, 0xcc, 0xf2, 0x2a,
	0xc7, 0x82, 0xc7, 0x03, 0x85, 0x66, 0x15, 0xa2, 0x0b, 0x2b, 0xfa, 0x6e, 0x51, 0xd2, 0x79, 0x3c,
	0x54, 0x5d, 0xa8, 0x45, 0x32, 0x85, 0xf0, 0x9c, 0xb2, 0x9f, 0xf2, 0x37, 0x39, 0x8f, 0x47, 0x32,
	0x3c, 0x2b, 0xeb, 0xb3, 0x57, 0x75, 0x9e, 0x61, 0x1c, 0x4a, 0x37, 0x2b, 0x0b, 0xc4, 0x4b, 0xac,
	0x99, 0xa8, 0xd7, 0x48, 0x8d, 0x07, 0x2d, 0x8a, 0x86, 0xcb, 0xd9, 0x51, 0x99, 0x17, 0x33, 0xca,
	0x30, 0x06, 0xd9, 0xd8, 0x8e, 0x86, 0x24, 0xb0, 0xa5, 0x62, 0x7e, 0xb5, 0x9c, 0x89, 0x96, 0xdd,
	0x94, 0xc8, 0x9e, 0x2e, 0xf9, 0x37, 0x80, 0xbe, 0x98, 0x5e, 0x77, 0xa2, 0x2e, 0x81, 0x2d, 0x31,
	0xf3, 0x6a, 0xbf, 0xe7, 0x3d, 0x9d, 0xb1, 0x31, 0x23, 0x4c, 0x93, 0xe9, 0xe9, 0x3c, 0x6a, 0x06,
	0x6b, 0xa8, 0x19, 0x5e, 0x4f, 0xcd, 0x68, 0x85, 0x1a, 0x86, 0x8b, 0x33, 0x9d, 0xb8, 0xa2, 0xd4,
	0xd1, 0x24, 0xef, 0x7b, 0x10, 0xd9, 0x96, 0xbf, 0xd7, 0xb2, 0x99, 0x42, 0xa8, 0x06, 0x48, 0x69,
	0x0a, 0xc7, 0xca, 0xe2, 0x2c, 0x2b, 0x0b, 0x5e, 0xd3, 0xcc, 0x54, 0x8e, 0x95, 0x3d, 0x0e, 0x86,
	0x6b, 0x38, 0x18, 0xb5, 0x38, 0x20, 0xd0, 0x9f, 0x53, 0x4e, 0x75, 0x8e, 0xf2, 0xf7, 0x9a, 0x92,
	0xf9, 0x1c, 0x1e, 0x9a, 0x68, 0x34, 0x37, 0x20, 0xfd, 0x5a, 0xda, 0xe4, 0xaf, 0x1e, 0x8c, 0xbd,
	0x41, 0xf2, 0x01, 0xb4, 0xd6, 0x5d, 0x19, 0x72, 0xd8, 0x08, 0x7d, 0x36, 0xda, 0x0d, 0x12, 0x75,
	0x34, 0xc8, 0xfb, 0x1e, 0x8c, 0xbd, 0x01, 0x74, 0xaf, 0x4c, 0x4c, 0x60, 0x90, 0x17, 0x73, 0x7c,
	0x2b, 0x89, 0xd8, 0x48, 0x95, 0xe0, 0xf0, 0x33, 0xb8, 0x9e, 0x9f, 0xe1, 0x3a, 0x7e, 0xee, 0x67,
	0xc0, 0xb4, 0xf9, 0x81, 0x55, 0x7e, 0x0e, 0xfe, 0xee, 0xc3, 0xf8, 0x4a, 0x6e, 0xb8, 0x27, 0x58,
	0x5f, 0x0a, 0xbc, 0xe7, 0x10, 0xd9, 0xad, 0x97, 0x4c, 0xc4, 0x00, 0x6f, 0xaf, 0xcc, 0xd3, 0x9d,
	0x96, 0x56, 0x3d, 0x02, 0xc9, 0x03, 0xf2, 0x35, 0x0c, 0xd5, 0xaa, 0x4a, 0xe4, 0xe4, 0xf7, 0x36,
	0xe0, 0x29, 0x71, 0x55, 0xd6, 0xe5, 0x08, 0xb6, 0xdc, 0xe5, 0x91, 0x7c, 0x22, 0x9f, 0x8c, 0xd5,
	0xb5, 0x75, 0x1a, 0xaf, 0x1e, 0x58, 0x90, 0x43, 0x08, 0xcd, 0x9e, 0x47, 0x1e, 0x1b, 0x3b, 0x67,
	0x9b, 0x9c, 0x4e, 0x7c, 0xa5, 0x75, 0xfc, 0x1e, 0xc6, 0xde, 0xa2, 0x41, 0xec, 0x2d, 0xed, 0x3d,
	0x67, 0xfa, 0xa4, 0xe3, 0xc4, 0xe2, 0xa4, 0xb0, 0xbd, 0xf2, 0xdc, 0x93, 0x5d, 0xe3, 0xd1, 0xb5,
	0x81, 0x4c, 0x3f, 0xbd, 0xe6, 0xb4, 0x8d, 0xe9, 0x57, 0xaf, 0xc5, 0xec, 0xda, 0x01, 0x1a, 0xcc,
	0xce, 0x57, 0x5a, 0xe5, 0xeb, 0xad, 0xa4, 0x2a, 0xdf, 0xae, 0x8d, 0x57, 0xe5, 0xdb, 0xb9, 0xbf,
	0x26, 0x0f, 0x66, 0x43, 0xf9, 0x9f, 0xea, 0x9b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x87,
	0x9e, 0xb2, 0x60, 0x0d, 0x00, 0x00,
}
